### ISSUE TITLE
Release 4.21

### ISSUE THREAD

**Issue by Y-Less** [Zeex/samp-plugin-crashdetect#104]
Unofficial release 4.21 until Zeex does, as it fixes a bug that people keep complaining about with YSI.  Integrates:

#101 and #98 

[crashdetect.zip](https://github.com/Zeex/samp-plugin-crashdetect/files/7998309/crashdetect.zip)

**Comment by Arose-Niazi** [comment]
This new update depends on `Failed (/lib32/libc.so.6: version `GLIBC_2.33' not found (required by plugins/crashdetect.so))`

Which is mess a get installed for Ubuntu 20.04 users.
