### ISSUE TITLE
Cannot load plugin..

### ISSUE THREAD

**Issue by JH3Y50N** [Zeex/samp-plugin-crashdetect#136]
I can't update to GLIBCXX_3.4.21, I can't change the operating system or update it

/lib/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /root/mdi/plugins/crashdetect.so)

**Comment by Zeex** [comment]
What OS are you using? CentOS 7?

You can try compiling from source code on your particular server or using this build from AppVeyor, which was compiled with an old version of GCC: https://ci.appveyor.com/api/buildjobs/sbed4na4vw9urhxn/artifacts/crashdetect-4.22-linux.tar.gz - this link will expire in 2 weeks though.

**Comment by JH3Y50N** [comment]
> What OS are you using? CentOS 7?
> 
> You can try compiling from source code on your particular server or using this build from AppVeyor, which was compiled with an old version of GCC: https://ci.appveyor.com/api/buildjobs/sbed4na4vw9urhxn/artifacts/crashdetect-4.22-linux.tar.gz - this link will expire in 2 weeks though.

yes, i'm on CentOS 7, thanks for it, i will test
