### ISSUE TITLE
Segfault when using crashdetect and y_inline

### ISSUE THREAD

**Issue by Misiur** [Zeex/samp-plugin-crashdetect#38]
If gamemode uses y_inline with "string:" type parameter, and crashdetect plugin is enabled, server segfaults. Without the plugin gdb doesn't report anything out of normal. Completely unhelpful GDB output as I can't even copy text from VM:
![Yadda yadda](http://i.imgur.com/YhTWRvg.png). 
Centos 6.6x32, selinux disabled (no idea if this makes any difference).

Example code used: https://gist.github.com/Misiur/01898cc095b52ee0b04f - mysql plugin isn't the cause, it's just handy to test callbacks.

**Comment by Zeex** [comment]
Do you have an example without MySQL?

**Comment by Misiur** [comment]
Sure, sorry. 

```pawn
#include <a_samp>
#include <YSI\y_inline>

main() {
}

public OnGameModeInit()
{
    inline Test(string:str[])
    {
        printf("WAT: %s", str);
    }

    ExampleInline(using inline Test);

    return 1;
}

ExampleInline(callback:func)
{
    static const
        str[64] = "Hello world!"
    ;
    new 
        inlineData[E_CALLBACK_DATA]
    ;

    Callback_Get(func, inlineData, "s");
    Callback_Call(inlineData, str);
    Callback_Release(inlineData);
}
```

Tried with -O0 as well, but no dice. No problems on windows with crashdetect enabled, Centos 6.6x32 works without crashdetect, fails when it's included.

**Comment by Zeex** [comment]
OK, thanks. 

It seems that there's something wrong with AmsEmitRetn() from asm.inc:

```
[debug] AMX backtrace:
[debug] #0 f7429fd6 in AsmError:AsmEmitInstruction (ctx[AsmContext:5]=@01046194, Opcode:opcode=48) at <unknown file>:0
[debug] #1 00004ca4 in AsmError:AsmEmitRetn (ctx[AsmContext:5]=@01046194) at Z:\/include/YSI/\YSI\..\YSI_Coding\..\amx\asm.inc:570
[debug] #2 0002d87c in Callback_Call (func[E_CALLBACK_DATA:5]=@010461c0, ... <1 argument>) at Z:\/include/YSI/\YSI\..\YSI_Coding\y_inline/impl.inc:568
[debug] #3 000333c8 in ExampleInline (callback_tag:func[]=@00006058) at y_inline.pwn:30
[debug] #4 00033320 in public ScriptInit_OnGameModeInit ()  at y_inline.pwn:16
[debug] #5 00006734 in public OnGameModeInit () at Z:\/include/YSI/\YSI\..\YSI_Coding\..\YSI_Storage\..\YSI_Internal\..\YSI_Server\y_scriptinit.inc:184
```

Sorry, I'm currently a little busy with work. I'll have a closer look on holidays.

**Comment by Zeex** [comment]
I found what's going on here:  y_inline uses `@emit SYSREQ` in some places, e.g.:

https://github.com/Y-Less/YSI-Includes/blob/YSI.tl/YSI_Coding/y_inline/impl.inc#L1142-1149

and since it's based on AsmEmitSysreqD() it won't work with crashdetect because RelocateOpcode() can't reliably relocate sysre.d opcodes:

https://github.com/Zeex/amx_assembly/blob/master/opcode.inc#L611-626

I think I'll update AsmEmitSysreq() to use sysreq.c since sysreq.d is broken anyway.

**Comment by Misiur** [comment]
That was fast, thank you. (TIL it's possible to select a range of lines in github)

**Comment by Zeex** [comment]
Yeah, took me several hours to debug the shit out of it, but it was kind of fun, even learned some new gdb commands...
