### ISSUE TITLE
Crashdetect subhook crash? or?

### ISSUE THREAD

**Issue by Kar2k** [Zeex/samp-plugin-crashdetect#39]
Linux debian 7

http://pastebin.com/sifrjKq5

**Comment by Zeex** [comment]
Did it load successfully?

**Comment by oscar-broman** [comment]
You could at least put some effort into making the issue.

What were you doing when it happened? What other plugins do you have loaded?

**Comment by Kar2k** [comment]
Sorry, I thought gdb would've given enough info.

Anyway I managed to recreate this by killing the server using (kill -9 pID)

plugins crashdetect.so mysql_static_r39.so streamer.so irc_debug.so sscanf.so Whirlpool.so MapAndreas.so socket.so nativechecker.so

**Comment by Zeex** [comment]
Strange, the server doesn't seem to be calling dlclose() when I kill it like that.

**Comment by oscar-broman** [comment]
I might add, though, that I experienced similar issues with the subhook C++ implementation (`hook` was `NULL` in `subhook_remove` error). I didn't make an issue because I wasn't sure if I was using it wrong. Switching to C made the issue go away.

**Comment by Kar2k** [comment]
Thats how I restart my server, finding the pIDs with ps aux then I use kill -9 pID (killing gdb plus the samp server).

Also zeex hmm.. try this

load mysql R39-2 static first then crashdetect then streamer.so, I got the output everytime it was loaded like that.

**Comment by oscar-broman** [comment]
Restarting with kill -9, that's just horrible.

**Comment by Kar2k** [comment]
Well give me a better solution. GMXing is out of the question due to sa-mp. I just kill the server so my auto restart script starts it again.

**Comment by oscar-broman** [comment]
`SendRconCommand("exit")`

You could script GDB to automatically quit when the SA-MP server didn't quit from a crash. You could probably script it to save the backtrace/dump to a file and quit even when something goes wrong.

**Comment by Kar2k** [comment]
gdb does all that already, it exists if the process doesn't exist anymore.

I use rcon exit once inawhile, I don't see a harmful difference though but ok.

**Comment by Kar2k** [comment]
I haven't seen this in awhile. Seems like it only happened for a week.
