### ISSUE TITLE
Build instructions (Linux)

### ISSUE THREAD

**Issue by selten** [Zeex/samp-plugin-crashdetect#41]
the make has to be done in the root folder apparently (according to the wiki it should be done in the build folder, but that doesn't work anyway).

http://pastebin.com/L3H51zYe
Output of make

therefore i think it's still incomplete

**Comment by Zeex** [comment]
There's no makefile in the root folder. The top-level makefile is the one generated in your build folder (the folder where you run cmake from).

**Comment by selten** [comment]
Did that, following error showed up in make: http://pastebin.com/eCMVYxcp

**Comment by Zeex** [comment]
That's interesting, I can't remember ever seeing int32_t defined in sys/types.h, it's usually stdint.h or inttypes.h. Which Linux distribution is this? CentOS?

**Comment by selten** [comment]
Debian

**Comment by Zeex** [comment]
What version of Debian? And what version of gcc are you using?

**Comment by selten** [comment]
gcc version 4.7.2
Distributor ID: Debian
Description:    Debian GNU/Linux 7.8 (wheezy)
Release:        7.8
Codename:       wheezy

**Comment by Zeex** [comment]
It compiled fine on my Debian 7.8 VM, I have no idea why it isn't compiling on your system. Anyway, removing those definitions of (u)int32_t from amx.h should allow you to build crashdetect,.
