### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by ATrigger** [Zeex/samp-plugin-crashdetect#46]
[ 97%] Building CXX object src/CMakeFiles/crashdetect.dir/stacktrace-win32.cpp.obj
mingw32-make.exe[2]: *** No rule to make target 'deps/lib/libpcred.a', needed by 'src/crashdetect.dll'.  Stop.
mingw32-make.exe[2]: *** Waiting for unfinished jobs....

**Comment by Zeex** [comment]
You need to use the MSVC (Visual Studio) compiler on WIndows, crashdetect currently can't be built with MinGW.
