### ISSUE TITLE
Invalid Memory Access

### ISSUE THREAD

**Issue by kylesmith09** [Zeex/samp-plugin-crashdetect#47]
I've an array for weapon data and when I access the array, it outputs:

[17:01:16] WEAPON_DATA[weaponid][WEP_BASE_DAMAGE] = 8.250000 and amount = 4.950000 - 29
[17:01:16] [debug] Run time error 5: "Invalid memory access"
[17:01:16] [debug] AMX backtrace:
[17:01:16] [debug] #0 00032a4c in public OnPlayerGiveDamage () at F:\Scripting - 0.3x\pawno\include\YSI\y_hooks/impl.inc:2420

The data from the array is right, I'm not sure how it's occuring?

I've the array if you'd like to see it but that'd have to be in private.

**Comment by oscar-broman** [comment]
Did you think to look at which file the error occurs?

Also, your printf output doesn't mean much to us.. We don't know what your code looks like.

**Comment by kylesmith09** [comment]
I did and the function is here:

http://pastebin.com/tQvP3dDD

It's line 38: return ret;.

That means nothing to me. The print may not mean nothing, but it proves there's nothing out of bounds, because it's accessing the array data.

**Comment by oscar-broman** [comment]
run pawndisasm to see which opcode cauaed it

**Comment by kylesmith09** [comment]
I removed the hook in the YSI to OPTS
D and it no longer occurs.

Kyle Smith

kyle@kylesmith.me.uk
07821113644
