### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by kylesmith09** [Zeex/samp-plugin-crashdetect#48]
Any idea why crashdetect isn't detecting the crashes:

This is what gdb debug is saying but I've no idea what's causing it:

crash.log: http://pastebin.com/aS88t3mr
lastcrash: http://pastebin.com/FJ2KUCY6

**Comment by Kar2k** [comment]
Don't use the latest crashdetect for now. I believe v4.15 and up isn't working. It actually is causing crashes.

**Comment by Zeex** [comment]
If you're running crashdetect under gdb it won't detect the crash because gdb gets the signal first and stops immediately. You usually use either one or the other but not both at once (unless you're debugging crashdetect itself).

**Comment by Kar2k** [comment]
I'd like to bump this, the latest crashdetect 4.15.1 does not report anything.. (windows and linux). Using your latest PAWN compiler.. 31/05/2015.
