### ISSUE TITLE
AMX_PATH maybe?

### ISSUE THREAD

**Issue by Sasuke-Uchiha** [Zeex/samp-plugin-crashdetect#53]
I have my scripts in following order

filterscripts-> (Scripts) These are debugged fine.
filterscripts/Missions ->(Scripts) these scripts just give me error but it's always <unknown>

So I can't either be sure it's due to that script or what.

All the scripts have crashdetect loaded as first include.
crashdetect is the first plugin.

-d3 compiler mode.

https://github.com/Zeex/samp-plugin-crashdetect/wiki/AMX-search-path-%28AMX_PATH%29

I found this function, but can't seem to understand how do I use it.

A example would help here.

Update tried these no use:
`AXM_PATH filterscripts/Test/ : ../filterscripts/Test/`
`AXM_PATH filterscripts/Test/`
`AXM_PATH ../filterscripts/Test/`
`AXM_PATH filterscripts/Test/Error`
`AXM_PATH filterscripts/Test/Error.amx`
These were last lines of server.cfg

The test script I used was
```
#include <a_samp>
#include <crashdetect>

public OnFilterScriptInit()
{
	for(new J=0; J < 5; J++)
	{
		back:
		new skin=random(312);
		if(skin == 74 || skin < 1) goto back;
		AddPlayerClassEx(J,J,0.0,0.0,5.0,0.0,0,24,50,0,0,0);
	}	
	return 1;
}
public OnPlayerRequestClass(playerid, classid)
{
	new array[1];
	array[0+classid]=-1;
	printf("%d",array[classid]);
	return 1;
}
```

I know this will cause error as this is a script I am trying on purpose.

Errors I get

> [11:47:44] [debug]  Attempted to read/write array element at index 3 in array of size 1
> [11:47:44] [debug] AMX backtrace:
> [11:47:44] [debug] #0 00000230 in public OnPlayerRequestClass (0, 3) from <unknown>

**Comment by Dayvison** [comment]
```pawn
{
	new array[5];
	array[0+classid]=-1;
	printf("%d",array[classid]);
	return 1;
}
```

**Comment by Zeex** [comment]
`AMX_PATH` is an environment variable. You can set environment variables via command line or if you're on Windows also via Control Panel (System -> Advanced -> Environment variables):

![env](https://cloud.githubusercontent.com/assets/1277375/21740526/5f4c55f6-d4e6-11e6-8d2f-a743fe861c9c.png)

**Comment by Zeex** [comment]
Assuming the problem was solved, if not feel free to open.
