### ISSUE TITLE
CMake Policy CMP0042 used despite the project's CMake version is 2.8.12

### ISSUE THREAD

**Issue by AGraber** [Zeex/samp-plugin-crashdetect#62]
CMP0042 was introduced in CMake 3.0

https://github.com/Zeex/samp-plugin-crashdetect/blob/f6826febf902e7f34bd4989d4f9b435e56c24c68/deps/subhook/CMakeLists.txt#L2

**Comment by Zeex** [comment]
Fixed, thanks.
