### ISSUE TITLE
Hang detection

### ISSUE THREAD

**Issue by Y-Less** [Zeex/samp-plugin-crashdetect#65]
I just came up with a way this could be used to detect and isolate infinite loops and the like, or even just very slow code:

1) Each time a public is called, make a note of the time.
2) Each time `break` is called, make a note of the time elapsed within that callback.
3) When this time passes some threshold print a warning with a traceback.
4) When the callback ends, clear the time.

The threshold need only be a few ms, possibly configurable, default 100ms to be safe.  For recurisve public calls such as via `CallLocalFunction`, I'd say don't apply this recursively - the time spent in the child publics still counts against the time spent in the original callback if the whole thing is slow.

**Comment by Zeex** [comment]
Sounds like a nice idea. 

BTW for debugging infinite loops one could send Ctrl-C/SIGINT to the server process to cause crashdetect to print a stack trace (and the server to exit). But I'm not sure if this still works, it may be broken on Linux or Windows (or both...).
