### ISSUE TITLE
Not showing function name where's occourring error.

### ISSUE THREAD

**Issue by BrunnoFdc** [Zeex/samp-plugin-crashdetect#68]
CrashDetect is showing this: 
```

[trace] public OnGameModeInit ()
[debug] Run time error 19: "File or function is not found"
[debug]
[debug]  î
[trace] main ()
[debug] Run time error 19: "File or function is not found"
[debug]
[debug]  î


```
I can't understand what it means. Can anyone help, please!

**Comment by Zeex** [comment]
Your *.amx file could be damaged, have you tried recompiling your script?

**Comment by BrunnoFdc** [comment]
Yes, various times, with the flag -d3.

I've found the problem: Was YSI. When I changed my YSI version with another one, the error has stopped to appear. But I don't know where the error is.
