### ISSUE TITLE
Binary attribution?

### ISSUE THREAD

**Issue by Daniel-Cortez** [Zeex/samp-plugin-crashdetect#69]
Currently CrashDetect is released under a 2-clause BSD license, which means that any compiled script (*.amx) that uses function `IsCrashDetectPresent()` from `crashdetect.inc` must somehow include a copy of CrashDetect's license text and the copyright notice.

> Copyright (c) 2013-2015 Zeex
> All rights reserved.
> (...)
> 2. **Redistributions in binary form must reproduce the above copyright notice,
>    this list of conditions and the following disclaimer in the documentation
>    and/or other materials provided with the distribution.**
> (...)

Not that I mind, but was this requirement really intended?

**Comment by Zeex** [comment]
I don't mind if somebody doesn't include that notice
