### ISSUE TITLE
Wrong file is reported

### ISSUE THREAD

**Issue by Y-Less** [Zeex/samp-plugin-crashdetect#70]
If you have a mode whose name is a prefix of the running mode, the prefix will appear in error messages.  I was testing `y_functional_gm.amx`, but also had `y_functional.amx` in the gamemodes directory.  The error message was:

```
[debug] Server crashed while executing y_functional.amx
[debug] AMX backtrace:
[debug] #0 0001e15c in public OnGameModeInit () at D:\work\SA-MP\pawno\include\YSI_Coding\y_functional\y_functional_rewrite.inc:205
[debug] Native backtrace:
[...]
```

(cropped because the actual error isn't important).  When I deleted `y_functional.amx` and restarted the server (with no other modifications, because it was already `_gm` that was running), the correct file was displayed:

```
[debug] Server crashed while executing y_functional_gm.amx
[debug] AMX backtrace:
[debug] #0 0001e15c in public OnGameModeInit () at D:\work\SA-MP\pawno\include\YSI_Coding\y_functional\y_functional_rewrite.inc:205
[debug] Native backtrace:
[...]
```

**Comment by Zeex** [comment]
Are you using the latest plugin version? Since 4.19+ crashdetect uses a different approach for *.amx file name detection, it should be more accurate.

**Comment by Y-Less** [comment]
I was on 4.18.1 (and can't even reproduce it now).
