### ISSUE TITLE
Hello, My server crashing for unknown reason 

### ISSUE THREAD

**Issue by Lamezy** [Zeex/samp-plugin-crashdetect#80]
Hello.
My server shut down after some time and the crashdetect shows me weird errors like this:

> [17:49:39] [debug] Server crashed due to an unknown error
> [17:49:39] [debug] Native backtrace:
> [17:49:39] [debug] #0 f73918b6 in _Z13GetStackTraceRSt6vectorI10StackFrameSaIS0_EEPv () in plugins/crashdetect.so
> [17:49:39] [debug] #1 f7389120 in _ZN18CrashDetectHandler20PrintNativeBacktraceERSoRKN2os7ContextE () in plugins/crashdetect.so
> [17:49:39] [debug] #2 f7389886 in _ZN18CrashDetectHandler20PrintNativeBacktraceERKN2os7ContextE () in plugins/crashdetect.so
> [17:49:39] [debug] #3 f7389f96 in _ZN18CrashDetectHandler7OnCrashERKN2os7ContextE () in plugins/crashdetect.so
> [17:49:39] [debug] #4 f7390f82 in ?? () in plugins/crashdetect.so
> [17:49:39] [debug] #5 f76f6410 in ?? ()
> [17:49:39] [debug] #6 f7402ff1 in _IO_vfprintf () in /lib/libc.so.6
> [17:49:39] [debug] #7 f7423702 in vsprintf () in /lib/libc.so.6
> [17:49:39] [debug] #8 f740866f in sprintf () in /lib/libc.so.6
> [17:49:39] [debug] #9 f725101d in _ZN11CMySQLQuery7ExecuteEP8st_mysql () in plugins/mysql.so
> [17:49:39] [debug] #10 f7246f09 in _ZN16CMySQLConnection14ProcessQueriesEv () in plugins/mysql.so
> [17:49:39] [debug] #11 f7248a27 in _ZN5boost6detail11thread_dataINS_3_bi6bind_tIvNS_4_mfi3mf0Iv16CMySQLConnectionEENS2_5list1INS2_5valueIPS6_EEEEEEE3runEv () in plugins/mysql.so
> [17:49:39] [debug] #12 f726de9d in ?? () in plugins/mysql.so
> [17:49:39] [debug] #13 f76d5bbc in ?? () in /lib/libpthread.so.0
> [17:49:39] [debug] #14 f74b80de in clone () in /lib/libc.so.6
> [17:49:39] [debug] Registers:
> [17:49:39] [debug] EAX: 00000000 EBX: f7581000 ECX: ffffffff EDX: b7ad951c
> [17:49:39] [debug] ESI: e48fe040 EDI: b7ad951c EBP: e48fe018 ESP: e48fdb00
> [17:49:39] [debug] EIP: f7402ff1 EFLAGS: 00010246
> [17:49:39] [debug] Stack:
> [17:49:39] [debug] ESP+00000000: e48fe040 f727bb5d 00000015 00000000
> [17:49:39] [debug] ESP+00000020: 00000000 00000000 00000000 00000000
> [17:49:39] [debug] ESP+00000040: 00000000 00000000 00000000 00000000
> [17:49:39] [debug] ESP+00000060: 00000000 00000000 00000000 00000000
> [17:49:39] [debug] ESP+00000080: 00000000 00000000 ffffffff 00000000
> [17:49:39] [debug] ESP+000000a0: 00000000 f74004c6 f757f260 00000000
> [17:49:39] [debug] ESP+000000c0: f727bb5d 00000000 000007d4 00000015
> [17:49:39] [debug] ESP+000000e0: 00000000 00000000 00000000 00000000
> [17:49:39] [debug] ESP+00000100: 00000000 00000000 00000000 00000000
> [17:49:39] [debug] ESP+00000120: 00000000 00000000 00000000 00000000
> [17:49:39] [debug] ESP+00000140: f07806cb 34f8cbf0 df270311 6b92f976
> [17:49:39] [debug] ESP+00000160: 4945050c e5a3b44a e086de07 fa5800b7
> [17:49:39] [debug] ESP+00000180: e48fdd38 00000000 0000000b e3502a40
> [17:49:39] [debug] ESP+000001a0: 0000000a e3502bd0 00004000 00000000
> [17:49:39] [debug] ESP+000001c0: e48fdd1c e3502bd0 00000000 f6cfbbf4
> [17:49:39] [debug] ESP+000001e0: f6cfbb69 f7152000 e48fdd98 f6cfbd00
> [17:49:39] [debug] ESP+00000200: e48fdd1c e48fddd8 e3506bf7 f7152000
> [17:49:39] [debug] ESP+00000220: e3506bd8 e3502bd4 00000007 ef459be6
> [17:49:39] [debug] ESP+00000240: 00000007 e35004f8 e48fdd68 f6cc436a
> [17:49:39] [debug] ESP+00000260: e35004f8 00000007 e48fdda8 f6cc4632
> [17:49:39] [debug] ESP+00000280: 00000007 e3500040 f6cfbc8b cbfe7400
> [17:49:39] [debug] ESP+000002a0: e35004f8 e48fddd0 e48fddf8 f6cc532f
> [17:49:39] [debug] ESP+000002c0: e48fde90 e48fde90 e48fde08 e35004f8
> [17:49:39] [debug] ESP+000002e0: 5f6a14fc 00000002 f6c78dda f75a0268
> [17:49:39] [debug] ESP+00000300: f75a060c f7701214 e48fde58 f6cb8cb5
> [17:49:39] [debug] ESP+00000320: e48fde50 03e4e303 e3500010 00000003
> [17:49:39] [debug] ESP+00000340: e27cf000 00002000 00000003 f7152000
> [17:49:39] [debug] ESP+00000360: 00000000 e3500040 e3500040 e350003c
> [17:49:39] [debug] ESP+00000380: 00002000 f74b1e89 00011ba8 e3500010
> [17:49:39] [debug] ESP+000003a0: f753ad3b 00001fe4 0000fee0 e3500010
> [17:49:39] [debug] ESP+000003c0: f753ad3b 00001000 f7432649 f7581000
> [17:49:39] [debug] ESP+000003e0: 00002710 e3500040 00000034 e3502a40
> [17:49:39] [debug] Loaded modules:
> [17:49:39] [debug] 00000000 - 00194f0b samp03svr
> [17:49:39] [debug] f76f8000 - f76f8530 
> [17:49:39] [debug] f76ea000 - f76ec6a4 /lib/libdl.so.2
> [17:49:39] [debug] f76cf000 - f76e8ad3 /lib/libpthread.so.0
> [17:49:39] [debug] f75e3000 - f76d4e88 /lib/libstdc++.so.6
> [17:49:39] [debug] f75a1000 - f75e2208 /lib/libm.so.6
> [17:49:39] [debug] f7585000 - f759e6f8 /lib/libgcc_s.so.1
> [17:49:39] [debug] f73ba000 - f758c8f3 /lib/libc.so.6
> [17:49:39] [debug] f76f7000 - f771a110 /lib/ld-linux.so.2
> [17:49:39] [debug] f7372000 - f73b63ac plugins/crashdetect.so
> [17:49:39] [debug] f7361000 - f73709b4 plugins/sscanf.so
> [17:49:39] [debug] f729b000 - f7360740 plugins/streamer.so
> [17:49:39] [debug] f728c000 - f7292d90 /lib/librt.so.1
> [17:49:39] [debug] f721a000 - f728c3eb plugins/mysql.so
> [17:49:39] [debug] f6c2d000 - f72441c0 /usr/lib/mysql/libmysqlclient.so.18
> [17:49:39] [debug] f6a1b000 - f6a2c748 /lib/libnss_files.so.2
> [17:49:39] [debug] f6810000 - f6819918 plugins/whirlpool.so
> [17:49:39] [debug] f76f0000 - f76f1f70 plugins/nativechecker.so
> [17:49:39] [debug] f676d000 - f6771d34 /lib/libnss_dns.so.2
> [17:49:39] [debug] f6754000 - f676c014 /lib/libresolv.so.2
> 

What does it mean ?

**Comment by Zeex** [comment]
I don't know. It seems to be related to mysql.so so you might want to check your MySQL queries.

**Comment by Lamezy** [comment]
Updating to R41 will solve it ?

**Comment by Zeex** [comment]
It has something to do with sprintf so I'd guess one of the "format" arguments in your mysql_query or whatever function calls is invalid. Or it could be something else. 

Anyway, upgrading the MySQL plugin shouldn't hurt.
