### ISSUE TITLE
Quick question

### ISSUE THREAD

**Issue by Cheaterman** [Zeex/samp-plugin-crashdetect#91]
Is it possible/normal that filterscripts would segfault crashdetect if compiled with -d2 instead of -d3? This used to be fine, but I changed compilers since then (I now use the modern one, that's picky about consts and whatnot).
Thanks in advance!

EDIT: Side question... If things complain about TEXTREL and -fPIC isn't good for SAMP stuff (is it?) should I use -nopie?

**Comment by Cheaterman** [comment]
I recompiled everything (as much as possible) with -fPIC and I can at least load crashdetect.so without immediately crashing, so I'm closing this. :-)

**Comment by Zeex** [comment]
Hmm, isn't it compiled by default with -fPIC with CMake? or you are not using CMake?

**Comment by Cheaterman** [comment]
@Zeex I suspect crashdetect wasn't the immediate issue, I since then recompiled some plugins with -fsanitize=address, used some valgrind etc, found quite a few really broken things to fix - I'm probably not done yet, I still hope crashdetect will point to more issues if I still have any, or I'll just swap plugins that are obviously faulty (after code review) for ones with cleaner code, hahaha. But if everything works here and is stable, that's good enough to me - either way, really not crashdetect's fault, despite the initial symptoms - possibly some non-PIC plugins trashing memory or stack :-)
